//
//  RegistrationWorker.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class RegistrationWorker {
    
    var errorAlertDelegate: ErrorAlert?
    var successAlertDelegate: SuccessAlert?
    
    func registerUserData(registerData: RegisterData, vc: UIViewController) {
        
        
        Auth.auth().createUser(withEmail: registerData.email, password: registerData.password) { [weak self] (authResult, error) in
            guard let _self = self else { return }
            if let err = error{
                _self.errorAlertDelegate?.alertError(message: err.localizedDescription)
            }
            else{
                
                guard let uid = authResult?.user.uid else { return }
                let imageName = NSUUID().uuidString
                let storageReference = Storage.storage().reference().child("profile_images/\(imageName).jpg")
                guard let image = registerData.profileImage.jpegData(compressionQuality: 0.1) else { return }
                
                storageReference.putData(image, metadata: nil) { [weak self] (metaData, error) in
                    guard let _self = self else { return }
                    
                    if let err = error{
                        _self.errorAlertDelegate?.alertError(message: err.localizedDescription)
                    }
                    else{
                        
                        storageReference.downloadURL { [unowned self] (url, error) in
                            
                            guard let downloadURL = url?.absoluteString else { return }
                    
                            let userReference = K.Reference.database.child(K.users).child(uid)
                            let values = [K.name: registerData.name, K.email: registerData.email, K.profileImageURL: downloadURL]
                            userReference.updateChildValues(values) { [weak self] (error, reference) in
                                guard let _self = self else { return }
                                
                                if let err = error{
                                    _self.errorAlertDelegate?.alertError(message: err.localizedDescription)
                                }
                                else{
                                    _self.successAlertDelegate?.alertSuccess(message: K.registered)
                                    vc.dismiss(animated: true, completion: nil)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
