//
//  ContactsRouter.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactsRoutingLogic {
    func routeToLoginOrRegisterScene()
    func routeToAddContactsScene(currentUserName: String)
    func routeToChatLogScene(contactDetail: AddContactsModel)
}

protocol ContactsDataPassing {
    var dataStore: ContactsDataStore! { get }
}

class ContactsRouter: NSObject, ContactsRoutingLogic, ContactsDataPassing {
    
    weak var viewController: ContactsViewController!
    var dataStore: ContactsDataStore!
    
    func routeToLoginOrRegisterScene() {
        
        let logInRegsiterVC = viewController.storyboard?.instantiateViewController(identifier: K.ViewControllers.logInOrRegister) as! LogInOrRegisterViewController
        navigateToLogInOrRegisterScene(source: viewController, destination: logInRegsiterVC)

    }
    
    func routeToAddContactsScene(currentUserName: String){
        
        let addContactsVc = viewController.storyboard?.instantiateViewController(identifier: K.ViewControllers.addContact) as! AddContactsViewController
        var addContactDS = addContactsVc.router!.dataStore!
        addContactsVc.contactsVC = viewController
        dataStore.currentUserName = currentUserName
        let navController = UINavigationController(rootViewController: addContactsVc)
        passDataToAddContactScene(source: dataStore, destination: &addContactDS)
        navigateToAddContactScene(source: viewController, destination: navController)
        
    }
    
    func routeToChatLogScene(contactDetail: AddContactsModel){
        
        let chatLogVc = viewController.storyboard?.instantiateViewController(identifier: K.ViewControllers.chatLog) as! ChatLogViewController
        dataStore.selectedNewContact = contactDetail
        var chatLogDS = chatLogVc.router!.dataStore!
        passDataToChatLogVC(source: dataStore, destination: &chatLogDS)
        navigateToChatLogScene(source: viewController, destination: chatLogVc)
    }
}

extension ContactsRouter {
    
        func passDataToChatLogVC(source: ContactsDataStore, destination: inout ChatLogDataStore) {
            
            destination.selectedNewContact = source.selectedNewContact
        }
    
    func passDataToAddContactScene(source: ContactsDataStore, destination: inout AddContactsDataStore) {
        
        destination.currentUser = source.currentUserName
    
    }
}

extension ContactsRouter {
    

    func navigateToLogInOrRegisterScene(source: ContactsViewController, destination: LogInOrRegisterViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToAddContactScene(source: ContactsViewController, destination: UINavigationController){
        
        destination.modalPresentationStyle = .fullScreen
        source.present(destination, animated: true, completion: nil)
    }
    
    func navigateToChatLogScene(source: ContactsViewController, destination: ChatLogViewController){
        
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
}
