//
//  ChatLogViewController.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/28/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

protocol ChatLogViewControllerInput: class {
    func displayMessage(viewModel: ChatLog.Message.Save.ViewModel)
    func displayChat(viewModel: ChatLog.Message.Load.ViewModel)
    func displayContactDetail(viewModel: ChatLog.NewContact.ViewModel)
}

protocol ChatLogViewControllerOutput {
    func sendMessage(request: ChatLog.Message.Save.Request)
    func loadChat(request: ChatLog.Message.Load.Request)
    func addContactDetail(request: ChatLog.NewContact.Request)
}

class ChatLogViewController: UIViewController {
    
    var output: ChatLogViewControllerOutput!
    var router: (NSObjectProtocol & ChatLogRoutingLogic & ChatLogDataPassing)!
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        configure()
    }
    
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
        configure()
    }
    
    private func configure(){
        ChatLogConfigurator.configure(viewController: self)
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    
    @IBOutlet weak var messageTextField: UITextField!
    @IBOutlet weak var chatsCollectionView: UICollectionView!
    
    var viewModel: ChatLog.Message.Load.ViewModel?
    let messagePartners = MessagePartners()
    var timer: Timer?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        output.addContactDetail(request: ChatLog.NewContact.Request())
        output.loadChat(request: ChatLog.Message.Load.Request())
        
        chatsCollectionView.alwaysBounceVertical = true
        chatsCollectionView.register(ChatCollectionViewCell.self, forCellWithReuseIdentifier: "ChatCell")
        chatsCollectionView.contentInset = UIEdgeInsets(top: 8, left: 0, bottom: 58, right: 0)
        chatsCollectionView.scrollIndicatorInsets = UIEdgeInsets(top: 0, left: 0, bottom: 50, right: 0)
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        output.loadChat(request: ChatLog.Message.Load.Request())
    }
    
    
    @IBAction func sendMessage(_ sender: Any) {
        
        guard let msg = messageTextField.text else { return }
        output.sendMessage(request: ChatLog.Message.Save.Request(messgae: msg))
        messageTextField.text = ""
    }
}

extension ChatLogViewController: ChatLogViewControllerInput {
    
    func displayMessage(viewModel: ChatLog.Message.Save.ViewModel) {
        
    }
    
    func displayContactDetail(viewModel: ChatLog.NewContact.ViewModel){
        
        self.navigationItem.title = viewModel.viewContactDetail.name
    }
    
    func displayChat(viewModel: ChatLog.Message.Load.ViewModel){
        
        self.viewModel = viewModel

        self.timer?.invalidate()
        self.timer = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(self.handleReloadtable), userInfo: nil, repeats: false)
    }
    
    @objc func handleReloadtable(){
        
        DispatchQueue.main.async{
            self.chatsCollectionView.reloadData()
        }
    }
}

extension ChatLogViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout{
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        
        return viewModel?.message.count ?? 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = chatsCollectionView.dequeueReusableCell(withReuseIdentifier: "ChatCell", for: indexPath) as! ChatCollectionViewCell
        guard let messageModel = viewModel?.message[indexPath.row] else { return cell}
        cell.textView.text = messageModel.text
        configureChats(cell: cell, message: messageModel, chatPartner: viewModel?.chatPartner)
        
        cell.bubbleWidthAnchor?.constant = estimateFrameForMessage(text: messageModel.text!).width + 32
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        var height: CGFloat = 80
        if let text = viewModel?.message[indexPath.row].text{
            height = estimateFrameForMessage(text: text).height + 20
        }
        return CGSize(width: view.frame.width , height: height)
    }
    
}


extension ChatLogViewController{
    
    private func estimateFrameForMessage(text: String) -> CGRect{
        
        let size = CGSize(width: 200, height: 1000)
        let options = NSStringDrawingOptions.usesFontLeading.union(.usesLineFragmentOrigin)
        return NSString(string: text).boundingRect(with: size, options: options, attributes: [ NSAttributedString.Key.font: UIFont.systemFont(ofSize: 16)], context: nil)
        
    }
    
    private func configureChats(cell: ChatCollectionViewCell, message: MessageModel, chatPartner: AddContactsViewModel?){
        
        guard let partnerImage = chatPartner?.profileImage else { return }
        cell.profileImageView.loadImageUsingCache(image: partnerImage)
        
        if message.fromID == Auth.auth().currentUser?.uid{
            
            cell.bubbleView.backgroundColor = ChatCollectionViewCell.blueColor
            cell.textView.textColor = .white
            cell.profileImageView.isHidden = true
            cell.bubbleRightAnchor?.isActive = true
            cell.bubbleLeftAnchor?.isActive = false
        }
        else{
            
            cell.bubbleView.backgroundColor = ChatCollectionViewCell.greyColor
            cell.textView.textColor = .black
            cell.profileImageView.isHidden = false
            cell.bubbleRightAnchor?.isActive = false
            cell.bubbleLeftAnchor?.isActive = true
        }
    }

}
