//
//  AddContactsRouter.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/15/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddContactsRoutingLogic {
    func routeBackToContacts()
}

protocol AddContactsDataPassing {
    var dataStore: AddContactsDataStore! { get }
}

class AddContactsRouter: NSObject, AddContactsRoutingLogic, AddContactsDataPassing {
    
    weak var viewController: AddContactsViewController!
    var dataStore: AddContactsDataStore!
    
    func routeBackToContacts(){
        
        navigateBackToContactsVC(source: viewController)
    }
}

extension AddContactsRouter {
    
}

extension AddContactsRouter {
    
   
    func navigateBackToContactsVC(source: AddContactsViewController) {
        
        source.dismiss(animated: true, completion: nil)
    }
}
