//
//  ChatLogRouter.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/28/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChatLogRoutingLogic {
    func routeToParentVC(segue: UIStoryboardSegue?)
}

protocol ChatLogDataPassing {
    var dataStore: ChatLogDataStore! { get }
    //func passDataToParentVC(source: ChatLogDataStore, destination: inout DestinationDataStore)
}

class ChatLogRouter: NSObject, ChatLogRoutingLogic, ChatLogDataPassing {
    
    weak var viewController: ChatLogViewController!
    var dataStore: ChatLogDataStore!
    
    // MARK: Routing
    func routeToParentVC(segue: UIStoryboardSegue?) {
        
//        guard let parentVC = segue.destination else {
//            return
//        }
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router.dataStore
//        passDataToParentVC(source: dataStore, destination: &destinationDS)
    }
}

extension ChatLogRouter {
    
    // MARK: Passing data
    //    func passDataToParentVC(source: ChatLogDataStore, destination: inout DestinationDataStore) {
    //
    //    }
}

extension ChatLogRouter {
    
    // MARK: Navigation
//    func navigateToParentVC(source: ChatLogViewController, destination: DestinationDataStore) {
//
//    }
}
