//
//  LogInWorker.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class LogInWorker {
    
    func logInUser(userData: LoginData, vc: UIViewController) {
        
        Auth.auth().signIn(withEmail: userData.email, password: userData.password) { (user, error) in
            
            if let error = error{
                print(error.localizedDescription)
            }
            else{
                
                print("Successfully Logged In")
                vc.dismiss(animated: true, completion: nil)
            }
        }
    }
}
