//
//  LogInWorker.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class LogInWorker {
    
    var alertErrorDelegate: ErrorAlert?
    var alertSuccessDelegate: SuccessAlert?
    
    func logInUser(userData: LoginData, vc: UIViewController) {
        
        Auth.auth().signIn(withEmail: userData.email, password: userData.password) { [weak self] (user, error) in
            guard let _self = self else { return }
            if let err = error{
                _self.alertErrorDelegate?.alertError(message: err.localizedDescription)
            }
            else{
                
                _self.alertSuccessDelegate?.alertSuccess(message: K.logged)
                vc.dismiss(animated: true, completion: nil)
            }
        }
    }
}
