//
//  LogInOrRegisterRouter.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LogInOrRegisterRoutingLogic {
    
    func sendDatatoRegisterationScene()
}

protocol LogInOrRegisterDataPassing {
    var dataStore: LogInOrRegisterDataStore! { get }
}

class LogInOrRegisterRouter: NSObject, LogInOrRegisterRoutingLogic, LogInOrRegisterDataPassing {


    weak var viewController: LogInOrRegisterViewController!
    var dataStore: LogInOrRegisterDataStore!

    
    func sendDatatoRegisterationScene(){
        
        let registrationVc = viewController.storyboard?.instantiateViewController(identifier: "RegistrationViewController") as! RegistrationViewController
        var registrationDS = registrationVc.router!.dataStore!
        passDataToRegistrationVC(source: dataStore, destination: &registrationDS)
    }
}

extension LogInOrRegisterRouter {
    
    // MARK: Passing data
        func passDataToRegistrationVC(source: LogInOrRegisterDataStore, destination: inout RegistrationDataStore) {
            
            //destination.profileImage = source.profileImage
            //print(destination.profileImage?.size)
        }
}

extension LogInOrRegisterRouter {
    
    // MARK: Navigation
//    func navigateToParentVC(source: LogInOrRegisterViewController, destination: DestinationDataStore) {
//
//    }
}
