//
//  LogInRouter.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LogInRoutingLogic {
    func routeToParentVC(segue: UIStoryboardSegue?)
}

protocol LogInDataPassing {
    var dataStore: LogInDataStore! { get }
    //func passDataToParentVC(source: LogInDataStore, destination: inout DestinationDataStore)
}

class LogInRouter: NSObject, LogInRoutingLogic, LogInDataPassing {
    
    weak var viewController: LogInViewController!
    var dataStore: LogInDataStore!
    
    // MARK: Routing
    func routeToParentVC(segue: UIStoryboardSegue?) {
        
//        guard let parentVC = segue.destination else {
//            return
//        }
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router.dataStore
//        passDataToParentVC(source: dataStore, destination: &destinationDS)
    }
}

extension LogInRouter {
    
    // MARK: Passing data
    //    func passDataToParentVC(source: LogInDataStore, destination: inout DestinationDataStore) {
    //
    //    }
}

extension LogInRouter {
    
    // MARK: Navigation
//    func navigateToParentVC(source: LogInViewController, destination: DestinationDataStore) {
//
//    }
}
