//
//  RegistrationRouter.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegistrationRoutingLogic {
    func routeToParentVC(segue: UIStoryboardSegue?)
}

protocol RegistrationDataPassing {
    var dataStore: RegistrationDataStore! { get }
    //func passDataToParentVC(source: RegistrationDataStore, destination: inout DestinationDataStore)
}

class RegistrationRouter: NSObject, RegistrationRoutingLogic, RegistrationDataPassing {
    
    weak var viewController: RegistrationViewController!
    var dataStore: RegistrationDataStore!
    
    // MARK: Routing
    func routeToParentVC(segue: UIStoryboardSegue?) {
        
//        guard let parentVC = segue.destination else {
//            return
//        }
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router.dataStore
//        passDataToParentVC(source: dataStore, destination: &destinationDS)
    }
}

extension RegistrationRouter {
    
    // MARK: Passing data
    //    func passDataToParentVC(source: RegistrationDataStore, destination: inout DestinationDataStore) {
    //
    //    }
}

extension RegistrationRouter {
    
    // MARK: Navigation
//    func navigateToParentVC(source: RegistrationViewController, destination: DestinationDataStore) {
//
//    }
}
