//
//  LogInViewController.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInViewControllerInput: class {
    func display(viewModel: LogIn.Fetch.ViewModel)
}

protocol LogInViewControllerOutput {
    func fetch(request: LogIn.Fetch.Request)
}

class LogInViewController: UIViewController {
    
    var output: LogInViewControllerOutput!
    var router: (NSObjectProtocol & LogInRoutingLogic & LogInDataPassing)!
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        configure()
    }
    
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
        configure()
    }
    
    private func configure(){
        LogInConfigurator.configure(viewController: self)
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    

    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
    
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
        
    @IBAction func logInUser(_ sender: Any) {
        guard let email = emailTextField.text, let password = passwordTextField.text else { return }
        let data = LoginData(email: email, password: password)
        output.fetch(request: LogIn.Fetch.Request(userData: data, viewController: self))
    }
    
}

extension LogInViewController: LogInViewControllerInput {
    
    func display(viewModel: LogIn.Fetch.ViewModel) {
        
    }
}
