//
//  LogInViewController.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInViewControllerInput: class {
    func displayErrorAlert(viewModel: LogIn.AlertMessage.Error.ViewModel)
    func displaySuccessAlert(viewModel: LogIn.AlertMessage.Success.ViewModel)
}

protocol LogInViewControllerOutput {
    func fetch(request: LogIn.Fetch.Request)
}

class LogInViewController: UIViewController {
    
    var output: LogInViewControllerOutput!
    var router: (NSObjectProtocol & LogInRoutingLogic & LogInDataPassing)!
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        configure()
    }
    
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
        configure()
    }
    
    private func configure(){
        LogInConfigurator.configure(viewController: self)
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    

    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
    
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
        
    @IBAction func logInUser(_ sender: Any) {
        guard let email = emailTextField.text, let password = passwordTextField.text else { return }
        let data = LoginData(email: email, password: password)
        output.fetch(request: LogIn.Fetch.Request(userData: data, viewController: self))
    }
    
    @objc func dismissAlert(){
        
        self.dismiss(animated: true, completion: nil)
    }

    
}

extension LogInViewController: LogInViewControllerInput {
    

    func displayErrorAlert(viewModel: LogIn.AlertMessage.Error.ViewModel){
        
        let alert = UIAlertController(title: K.alert, message: viewModel.message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: K.okay, style: .cancel, handler: { (action) in
            self.emailTextField.text = K.empty
            self.passwordTextField.text = K.empty
        }))

        self.present(alert, animated: true, completion: nil)
    }
    
    func displaySuccessAlert(viewModel: LogIn.AlertMessage.Success.ViewModel){
        
        let alert = UIAlertController(title:K.empty, message: viewModel.message, preferredStyle: .alert)
        emailTextField.text = K.empty
        passwordTextField.text = K.empty
        self.present(alert, animated: true, completion: nil)
        Timer.scheduledTimer(timeInterval: 2.0, target: self, selector: #selector(dismissAlert), userInfo: nil, repeats: false)
        
    }
}
