//
//  RegistrationViewController.swift
//  Game'OChat
//
//  Created by Roushil singla on 2/11/20.
//  Copyright (c) 2020 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationViewControllerInput: class {
    func displayAlertError(viewModel: Registration.AlertMessage.Error.ViewModel)
    func displayAlertSuccess(viewModel: Registration.AlertMessage.Success.ViewModel)
}

protocol RegistrationViewControllerOutput {
    func fetch(request: Registration.Fetch.Request)
}

class RegistrationViewController: UIViewController {
    
    var output: RegistrationViewControllerOutput!
    var router: (NSObjectProtocol & RegistrationRoutingLogic & RegistrationDataPassing)!
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        configure()
    }
    
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
        configure()
    }
    
    private func configure(){
        RegistrationConfigurator.configure(viewController: self)
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK:- IBOutlet properties
    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var profileImageView: UIImageView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        profileImageView.image = UIImage(named: "blank_profile")
        uploadProfileImage()
    }
    
    
    @IBAction func registerUser(_ sender: Any) {
        
        guard let name = nameTextField.text,let email = emailTextField.text,let password = passwordTextField.text, let profileImage = profileImageView.image else { return }
        output.fetch(request: Registration.Fetch.Request(registerData: RegisterData(name: name, email: email, password: password, profileImage: profileImage), viewcontroller: self))
    }
    
}

extension RegistrationViewController: RegistrationViewControllerInput {
    
    
    func displayAlertError(viewModel: Registration.AlertMessage.Error.ViewModel){
        
        let alert = UIAlertController(title: "Alert", message: viewModel.message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        self.present(alert, animated: true, completion: nil)

    }
    
    func displayAlertSuccess(viewModel: Registration.AlertMessage.Success.ViewModel){
        
        let alert = UIAlertController(title:"", message: viewModel.message, preferredStyle: .alert)
        self.present(alert, animated: true, completion: nil)
        Timer.scheduledTimer(timeInterval: 2.0, target: self, selector: #selector(dismissAlert), userInfo: nil, repeats: false)

    }
}

extension RegistrationViewController{
    
    func uploadProfileImage(){
        
        profileImageView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(uploadImage)))
        profileImageView.isUserInteractionEnabled = true
    }
    
    @objc func dismissAlert(){
        
        self.dismiss(animated: true, completion: nil)
    }
}

extension RegistrationViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate{
    
    @objc func uploadImage(){
        
        let picker = UIImagePickerController()
        picker.allowsEditing = true
        picker.delegate = self
        present(picker, animated: true, completion: nil)
    }
    
    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
        
        var selectedImage: UIImage?
        
        if let editedImage = info[UIImagePickerController.InfoKey.editedImage] as? UIImage{
            selectedImage = editedImage
        } else if let originalImage = info[UIImagePickerController.InfoKey.originalImage] as? UIImage{
            selectedImage = originalImage
        }
        profileImageView.contentMode = .scaleAspectFill
        profileImageView.image = selectedImage
        dismiss(animated: true, completion: nil)
    }
    
}

